

// Gradle project data. The build directory is useful for importing built files.
gradle.build-dir = /home/eshome33/IdeaProjects/watersort/build
gradle.project-name = watersort
app.fsname = watersort
app.version = 1.1
app.rdns-name = fr.eshome.${app.fsname}
app.machines = [windows.amd64, linux.amd64.glibc]
app.site.base-url = "localhost"

// Config from the OpenJFX plugin.
include required("/stdlib/jvm/javafx/from-jmods.conf")
javafx.version = 21.0.12
app.jvm.modules = ${app.jvm.modules} [javafx.controls, javafx.fxml, jdk.random]

// Config from the application plugin.
app.jvm.gui.main-class = fr.eshome.watersort.GameApplication
app.linux.desktop-file."Desktop Entry".StartupWMClass = fr.eshome.watersort.GameApplication

// Config from the Java plugin.
include required("/stdlib/jdk/21/openjdk.conf")

// Config from the Jetpack Compose Desktop plugin.

// Inputs from dependency configurations and the JAR task.
app.inputs += /home/eshome33/IdeaProjects/watersort/build/libs/watersort-1.1.jar
app.inputs = ${app.inputs} [
  /home/eshome33/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.14.0/efc0e34ede4e3204eaefb84a00e55e8c86634382/gson-2.14.0.jar
  /home/eshome33/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.48.0/bbe30942a31d1778c74cb272321267eca82dc708/error_prone_annotations-2.48.0.jar
]


conveyor.compatibility-level = 22
