include required("generated.conveyor.conf")


app.machines = [windows.amd64, linux.amd64.glibc]
app.site.base-url = "http://localhost"
app.vendor = "ESHome33"
app.display-name = "Water Sort"
app.description = "A relaxing water sorting puzzle game"
app.license = "MIT"
app.contact-email = "eshome.fr@gmail.com"

app.jvm.modules = ${app.jvm.modules} [jdk.random]

conveyor.compatibility-level = 22
